namespace FSharp.Html.Dsl.Tests

module Html =

    open FSharp.Html.Dsl
    open FsUnit.Xunit
    open Xunit

    [<Fact>]
    let ``Elements`` () =
        _html [] [] |> should equal <| Elem.html [] []
        _base [] |> should equal <| Elem.base' []
        _head [] [] |> should equal <| Elem.head [] []
        _link [] |> should equal <| Elem.link []
        _meta [] |> should equal <| Elem.meta []
        _style [] [] |> should equal <| Elem.style [] []
        _title [] [] |> should equal <| Elem.title [] []
        _body [] [] |> should equal <| Elem.body [] []
        _address [] [] |> should equal <| Elem.address [] []
        _article [] [] |> should equal <| Elem.article [] []
        _aside [] [] |> should equal <| Elem.aside [] []
        _footer [] [] |> should equal <| Elem.footer [] []
        _header [] [] |> should equal <| Elem.header [] []
        _h1 [] [] |> should equal <| Elem.h1 [] []
        _h2 [] [] |> should equal <| Elem.h2 [] []
        _h3 [] [] |> should equal <| Elem.h3 [] []
        _h4 [] [] |> should equal <| Elem.h4 [] []
        _h5 [] [] |> should equal <| Elem.h5 [] []
        _h6 [] [] |> should equal <| Elem.h6 [] []
        _main [] [] |> should equal <| Elem.main [] []
        _nav [] [] |> should equal <| Elem.nav [] []
        _section [] [] |> should equal <| Elem.section [] []
        _blockquote [] [] |> should equal <| Elem.blockquote [] []
        _dd [] [] |> should equal <| Elem.dd [] []
        _div [] [] |> should equal <| Elem.div [] []
        _dl [] [] |> should equal <| Elem.dl [] []
        _dt [] [] |> should equal <| Elem.dt [] []
        _figcaption [] [] |> should equal <| Elem.figcaption [] []
        _figure [] [] |> should equal <| Elem.figure [] []
        _hr [] |> should equal <| Elem.hr []
        _li [] [] |> should equal <| Elem.li [] []
        _menu [] [] |> should equal <| Elem.menu [] []
        _ol [] [] |> should equal <| Elem.ol [] []
        _p [] [] |> should equal <| Elem.p [] []
        _pre [] [] |> should equal <| Elem.pre [] []
        _ul [] [] |> should equal <| Elem.ul [] []
        _a [] [] |> should equal <| Elem.a [] []
        _abbr [] [] |> should equal <| Elem.abbr [] []
        _b [] [] |> should equal <| Elem.b [] []
        _bdi [] [] |> should equal <| Elem.bdi [] []
        _bdo [] [] |> should equal <| Elem.bdo [] []
        _br [] |> should equal <| Elem.br []
        _cite [] [] |> should equal <| Elem.cite [] []
        _code [] [] |> should equal <| Elem.code [] []
        _data [] [] |> should equal <| Elem.data [] []
        _dfn [] [] |> should equal <| Elem.dfn [] []
        _em [] [] |> should equal <| Elem.em [] []
        _i [] [] |> should equal <| Elem.i [] []
        _kbd [] [] |> should equal <| Elem.kbd [] []
        _mark [] [] |> should equal <| Elem.mark [] []
        _q [] [] |> should equal <| Elem.q [] []
        _rp [] [] |> should equal <| Elem.rp [] []
        _rt [] [] |> should equal <| Elem.rt [] []
        _ruby [] [] |> should equal <| Elem.ruby [] []
        _s [] [] |> should equal <| Elem.s [] []
        _samp [] [] |> should equal <| Elem.samp [] []
        _small [] [] |> should equal <| Elem.small [] []
        _span [] [] |> should equal <| Elem.span [] []
        _strong [] [] |> should equal <| Elem.strong [] []
        _sub [] [] |> should equal <| Elem.sub [] []
        _sup [] [] |> should equal <| Elem.sup [] []
        _time [] [] |> should equal <| Elem.time [] []
        _u [] [] |> should equal <| Elem.u [] []
        _var [] [] |> should equal <| Elem.var [] []
        _wbr [] |> should equal <| Elem.wbr []
        _area [] [] |> should equal <| Elem.area [] []
        _audio [] [] |> should equal <| Elem.audio [] []
        _img [] |> should equal <| Elem.img []
        _map [] [] |> should equal <| Elem.map [] []
        _track [] |> should equal <| Elem.track []
        _video [] [] |> should equal <| Elem.video [] []
        _embed [] |> should equal <| Elem.embed []
        _iframe [] [] |> should equal <| Elem.iframe [] []
        _object [] [] |> should equal <| Elem.object [] []
        _picture [] [] |> should equal <| Elem.picture [] []
        _portal [] [] |> should equal <| Elem.portal [] []
        _source [] |> should equal <| Elem.source []
        _canvas [] [] |> should equal <| Elem.canvas [] []
        _noscript [] [] |> should equal <| Elem.noscript [] []
        _script [] [] |> should equal <| Elem.script [] []
        _del [] [] |> should equal <| Elem.del [] []
        _ins [] [] |> should equal <| Elem.ins [] []
        _caption [] [] |> should equal <| Elem.caption [] []
        _col [] |> should equal <| Elem.col []
        _colgroup [] [] |> should equal <| Elem.colgroup [] []
        _table [] [] |> should equal <| Elem.table [] []
        _tbody [] [] |> should equal <| Elem.tbody [] []
        _td [] [] |> should equal <| Elem.td [] []
        _tfoot [] [] |> should equal <| Elem.tfoot [] []
        _th [] [] |> should equal <| Elem.th [] []
        _thead [] [] |> should equal <| Elem.thead [] []
        _tr [] [] |> should equal <| Elem.tr [] []
        _button [] [] |> should equal <| Elem.button [] []
        _datalist [] [] |> should equal <| Elem.datalist [] []
        _fieldset [] [] |> should equal <| Elem.fieldset [] []
        _form [] [] |> should equal <| Elem.form [] []
        _input [] |> should equal <| Elem.input []
        _label [] [] |> should equal <| Elem.label [] []
        _legend [] [] |> should equal <| Elem.legend [] []
        _meter [] [] |> should equal <| Elem.meter [] []
        _optgroup [] [] |> should equal <| Elem.optgroup [] []
        _option [] [] |> should equal <| Elem.option [] []
        _output [] [] |> should equal <| Elem.output [] []
        _progress [] [] |> should equal <| Elem.progress [] []
        _select [] [] |> should equal <| Elem.select [] []
        _textarea [] [] |> should equal <| Elem.textarea [] []
        _details [] [] |> should equal <| Elem.details [] []
        _dialog [] [] |> should equal <| Elem.dialog [] []
        _summary [] [] |> should equal <| Elem.summary [] []
        _slot [] [] |> should equal <| Elem.slot [] []
        _template [] [] |> should equal <| Elem.template [] []
        _math [] [] |> should equal <| Elem.math [] []
        _svg [] [] |> should equal <| Elem.svg [] []

    [<Fact>]
    let ``Text`` () =
        _text "fsharp" |> should equal <| Text.raw "fsharp"
        _textf "fsharp %s" "rocks" |> should equal <| Text.rawf "fsharp %s" "rocks"
        _textEnc "fsharp" |> should equal <| Text.enc "fsharp"   

    [<Fact>]
    let ``Attributes`` () =
        _div [ _accept_ "fsharp" ] [] |> should equal <| _div [ Attr.accept "fsharp" ] []
        _div [ _acceptCharset_ "fsharp" ] [] |> should equal <| _div [ Attr.acceptCharset "fsharp" ] []
        _div [ _accesskey_ "fsharp" ] [] |> should equal <| _div [ Attr.accesskey "fsharp" ] []
        _div [ _action_ "fsharp" ] [] |> should equal <| _div [ Attr.action "fsharp" ] []
        _div [ _align_ "fsharp" ] [] |> should equal <| _div [ Attr.align "fsharp" ] []
        _div [ _allow_ "fsharp" ] [] |> should equal <| _div [ Attr.allow "fsharp" ] []
        _div [ _alt_ "fsharp" ] [] |> should equal <| _div [ Attr.alt "fsharp" ] []
        _div [ _aria_ "value" "fsharp" ] [] |> should equal <| _div [ Attr.aria "value" "fsharp" ] []
        _div [ _async_ ] [] |> should equal <| _div [ Attr.async ] []
        _div [ _autocapitalize_ "fsharp" ] [] |> should equal <| _div [ Attr.autocapitalize "fsharp" ] []
        _div [ _autocomplete_ "fsharp" ] [] |> should equal <| _div [ Attr.autocomplete "fsharp" ] []
        _div [ _autofocus_ ] [] |> should equal <| _div [ Attr.autofocus ] []
        _div [ _autoplay_ ] [] |> should equal <| _div [ Attr.autoplay ] []
        _div [ _background_ "fsharp" ] [] |> should equal <| _div [ Attr.background "fsharp" ] []
        _div [ _bgcolor_ "fsharp" ] [] |> should equal <| _div [ Attr.bgcolor "fsharp" ] []
        _div [ _border_ "fsharp" ] [] |> should equal <| _div [ Attr.border "fsharp" ] []
        _div [ _buffered_ "fsharp" ] [] |> should equal <| _div [ Attr.buffered "fsharp" ] []
        _div [ _capture_ "fsharp" ] [] |> should equal <| _div [ Attr.capture "fsharp" ] []
        _div [ _challenge_ "fsharp" ] [] |> should equal <| _div [ Attr.challenge "fsharp" ] []
        _div [ _charset_ "fsharp" ] [] |> should equal <| _div [ Attr.charset "fsharp" ] []
        _div [ _checked_  ] [] |> should equal <| _div [ Attr.checked' ] []
        _div [ _cite_ "fsharp" ] [] |> should equal <| _div [ Attr.cite "fsharp" ] []
        _div [ _class_ "fsharp" ] [] |> should equal <| _div [ Attr.class' "fsharp" ] []
        _div [ _code_ "fsharp" ] [] |> should equal <| _div [ Attr.code "fsharp" ] []
        _div [ _codebase_ "fsharp" ] [] |> should equal <| _div [ Attr.codebase "fsharp" ] []
        _div [ _color_ "fsharp" ] [] |> should equal <| _div [ Attr.color "fsharp" ] []
        _div [ _cols_ "fsharp" ] [] |> should equal <| _div [ Attr.cols "fsharp" ] []
        _div [ _colspan_ "fsharp" ] [] |> should equal <| _div [ Attr.colspan "fsharp" ] []
        _div [ _content_ "fsharp" ] [] |> should equal <| _div [ Attr.content "fsharp" ] []
        _div [ _contenteditable_ "fsharp" ] [] |> should equal <| _div [ Attr.contenteditable "fsharp" ] []
        _div [ _contextmenu_ "fsharp" ] [] |> should equal <| _div [ Attr.contextmenu "fsharp" ] []
        _div [ _controls_ ] [] |> should equal <| _div [ Attr.controls ] []
        _div [ _coords_ "fsharp" ] [] |> should equal <| _div [ Attr.coords "fsharp" ] []
        _div [ _crossorigin_ "fsharp" ] [] |> should equal <| _div [ Attr.crossorigin "fsharp" ] []
        _div [ _csp_ "fsharp" ] [] |> should equal <| _div [ Attr.csp "fsharp" ] []
        _div [ _data_ "value" "fsharp" ] [] |> should equal <| _div [ Attr.data "value" "fsharp" ] []
        _div [ _datetime_ "fsharp" ] [] |> should equal <| _div [ Attr.datetime "fsharp" ] []
        _div [ _decoding_ "fsharp" ] [] |> should equal <| _div [ Attr.decoding "fsharp" ] []
        _div [ _default_  ] [] |> should equal <| _div [ Attr.default' ] []
        _div [ _defer_ ] [] |> should equal <| _div [ Attr.defer ] []
        _div [ _dir_ "fsharp" ] [] |> should equal <| _div [ Attr.dir "fsharp" ] []
        _div [ _dirname_ "fsharp" ] [] |> should equal <| _div [ Attr.dirname "fsharp" ] []
        _div [ _disabled_ ] [] |> should equal <| _div [ Attr.disabled ] []
        _div [ _download_ "fsharp" ] [] |> should equal <| _div [ Attr.download "fsharp" ] []
        _div [ _draggable_ "fsharp" ] [] |> should equal <| _div [ Attr.draggable "fsharp" ] []
        _div [ _enctype_ "fsharp" ] [] |> should equal <| _div [ Attr.enctype "fsharp" ] []
        _div [ _enterkeyhint_ "fsharp" ] [] |> should equal <| _div [ Attr.enterkeyhint "fsharp" ] []
        _div [ _for_ "fsharp" ] [] |> should equal <| _div [ Attr.for' "fsharp" ] []
        _div [ _form_ "fsharp" ] [] |> should equal <| _div [ Attr.form "fsharp" ] []
        _div [ _formaction_ "fsharp" ] [] |> should equal <| _div [ Attr.formaction "fsharp" ] []
        _div [ _formenctype_ "fsharp" ] [] |> should equal <| _div [ Attr.formenctype "fsharp" ] []
        _div [ _formmethod_ "fsharp" ] [] |> should equal <| _div [ Attr.formmethod "fsharp" ] []
        _div [ _formnovalidate_ ] [] |> should equal <| _div [ Attr.formnovalidate ] []
        _div [ _formtarget_ "fsharp" ] [] |> should equal <| _div [ Attr.formtarget "fsharp" ] []
        _div [ _headers_ "fsharp" ] [] |> should equal <| _div [ Attr.headers "fsharp" ] []
        _div [ _height_ "fsharp" ] [] |> should equal <| _div [ Attr.height "fsharp" ] []
        _div [ _hidden_ ] [] |> should equal <| _div [ Attr.hidden ] []
        _div [ _high_ "fsharp" ] [] |> should equal <| _div [ Attr.high "fsharp" ] []
        _div [ _href_ "fsharp" ] [] |> should equal <| _div [ Attr.href "fsharp" ] []
        _div [ _hreflang_ "fsharp" ] [] |> should equal <| _div [ Attr.hreflang "fsharp" ] []
        _div [ _httpEquiv_ "fsharp" ] [] |> should equal <| _div [ Attr.httpEquiv "fsharp" ] []
        _div [ _icon_ "fsharp" ] [] |> should equal <| _div [ Attr.icon "fsharp" ] []
        _div [ _id_ "fsharp" ] [] |> should equal <| _div [ Attr.id "fsharp" ] []
        _div [ _importance_ "fsharp" ] [] |> should equal <| _div [ Attr.importance "fsharp" ] []
        _div [ _integrity_ "fsharp" ] [] |> should equal <| _div [ Attr.integrity "fsharp" ] []
        _div [ _inputmode_ "fsharp" ] [] |> should equal <| _div [ Attr.inputmode "fsharp" ] []
        _div [ _ismap_ ] [] |> should equal <| _div [ Attr.ismap ] []
        _div [ _itemprop_ "fsharp" ] [] |> should equal <| _div [ Attr.itemprop "fsharp" ] []
        _div [ _keytype_ "fsharp" ] [] |> should equal <| _div [ Attr.keytype "fsharp" ] []
        _div [ _kind_ "fsharp" ] [] |> should equal <| _div [ Attr.kind "fsharp" ] []
        _div [ _label_ "fsharp" ] [] |> should equal <| _div [ Attr.label "fsharp" ] []
        _div [ _lang_ "fsharp" ] [] |> should equal <| _div [ Attr.lang "fsharp" ] []
        _div [ _loading_ "fsharp" ] [] |> should equal <| _div [ Attr.loading "fsharp" ] []
        _div [ _list_ "fsharp" ] [] |> should equal <| _div [ Attr.list "fsharp" ] []
        _div [ _loop_ ] [] |> should equal <| _div [ Attr.loop ] []
        _div [ _low_ "fsharp" ] [] |> should equal <| _div [ Attr.low "fsharp" ] []
        _div [ _max_ "fsharp" ] [] |> should equal <| _div [ Attr.max "fsharp" ] []
        _div [ _maxlength_ "fsharp" ] [] |> should equal <| _div [ Attr.maxlength "fsharp" ] []
        _div [ _minlength_ "fsharp" ] [] |> should equal <| _div [ Attr.minlength "fsharp" ] []
        _div [ _media_ "fsharp" ] [] |> should equal <| _div [ Attr.media "fsharp" ] []
        _div [ _method_ "fsharp" ] [] |> should equal <| _div [ Attr.method "fsharp" ] []
        _div [ _min_ "fsharp" ] [] |> should equal <| _div [ Attr.min "fsharp" ] []
        _div [ _multiple_ ] [] |> should equal <| _div [ Attr.multiple ] []
        _div [ _muted_ ] [] |> should equal <| _div [ Attr.muted ] []
        _div [ _name_ "fsharp" ] [] |> should equal <| _div [ Attr.name "fsharp" ] []
        _div [ _novalidate_ ] [] |> should equal <| _div [ Attr.novalidate ] []
        _div [ _open_ "fsharp" ] [] |> should equal <| _div [ Attr.open' "fsharp" ] []
        _div [ _optimum_ "fsharp" ] [] |> should equal <| _div [ Attr.optimum "fsharp" ] []
        _div [ _pattern_ "fsharp" ] [] |> should equal <| _div [ Attr.pattern "fsharp" ] []
        _div [ _ping_ "fsharp" ] [] |> should equal <| _div [ Attr.ping "fsharp" ] []
        _div [ _placeholder_ "fsharp" ] [] |> should equal <| _div [ Attr.placeholder "fsharp" ] []
        _div [ _poster_ "fsharp" ] [] |> should equal <| _div [ Attr.poster "fsharp" ] []
        _div [ _preload_ "fsharp" ] [] |> should equal <| _div [ Attr.preload "fsharp" ] []
        _div [ _radiogroup_ "fsharp" ] [] |> should equal <| _div [ Attr.radiogroup "fsharp" ] []
        _div [ _readonly_ ] [] |> should equal <| _div [ Attr.readonly ] []
        _div [ _referrerpolicy_ "fsharp" ] [] |> should equal <| _div [ Attr.referrerpolicy "fsharp" ] []
        _div [ _rel_ "fsharp" ] [] |> should equal <| _div [ Attr.rel "fsharp" ] []
        _div [ _required_ ] [] |> should equal <| _div [ Attr.required ] []
        _div [ _reversed_ ] [] |> should equal <| _div [ Attr.reversed ] []
        _div [ _role_ "fsharp" ] [] |> should equal <| _div [ Attr.role "fsharp" ] []
        _div [ _rows_ "fsharp" ] [] |> should equal <| _div [ Attr.rows "fsharp" ] []
        _div [ _rowspan_ "fsharp" ] [] |> should equal <| _div [ Attr.rowspan "fsharp" ] []
        _div [ _sandbox_ "fsharp" ] [] |> should equal <| _div [ Attr.sandbox "fsharp" ] []
        _div [ _scope_ "fsharp" ] [] |> should equal <| _div [ Attr.scope "fsharp" ] []
        _div [ _selected_ ] [] |> should equal <| _div [ Attr.selected ] []
        _div [ _shape_ "fsharp" ] [] |> should equal <| _div [ Attr.shape "fsharp" ] []
        _div [ _size_ "fsharp" ] [] |> should equal <| _div [ Attr.size "fsharp" ] []
        _div [ _sizes_ "fsharp" ] [] |> should equal <| _div [ Attr.sizes "fsharp" ] []
        _div [ _slot_ "fsharp" ] [] |> should equal <| _div [ Attr.slot "fsharp" ] []
        _div [ _span_ "fsharp" ] [] |> should equal <| _div [ Attr.span "fsharp" ] []
        _div [ _spellcheck_ "fsharp" ] [] |> should equal <| _div [ Attr.spellcheck "fsharp" ] []
        _div [ _src_ "fsharp" ] [] |> should equal <| _div [ Attr.src "fsharp" ] []
        _div [ _srcdoc_ "fsharp" ] [] |> should equal <| _div [ Attr.srcdoc "fsharp" ] []
        _div [ _srclang_ "fsharp" ] [] |> should equal <| _div [ Attr.srclang "fsharp" ] []
        _div [ _srcset_ "fsharp" ] [] |> should equal <| _div [ Attr.srcset "fsharp" ] []
        _div [ _start_ "fsharp" ] [] |> should equal <| _div [ Attr.start "fsharp" ] []
        _div [ _step_ "fsharp" ] [] |> should equal <| _div [ Attr.step "fsharp" ] []
        _div [ _style_ "fsharp" ] [] |> should equal <| _div [ Attr.style "fsharp" ] []
        _div [ _tabindex_ "fsharp" ] [] |> should equal <| _div [ Attr.tabindex "fsharp" ] []
        _div [ _target_ "fsharp" ] [] |> should equal <| _div [ Attr.target "fsharp" ] []
        _div [ _title_ "fsharp" ] [] |> should equal <| _div [ Attr.title "fsharp" ] []
        _div [ _translate_ "fsharp" ] [] |> should equal <| _div [ Attr.translate "fsharp" ] []
        _div [ _type_ "fsharp" ] [] |> should equal <| _div [ Attr.type' "fsharp" ] []
        _div [ _usemap_ "fsharp" ] [] |> should equal <| _div [ Attr.usemap "fsharp" ] []
        _div [ _value_ "fsharp" ] [] |> should equal <| _div [ Attr.value "fsharp" ] []
        _div [ _width_ "fsharp" ] [] |> should equal <| _div [ Attr.width "fsharp" ] []
        _div [ _wrap_ "fsharp" ] [] |> should equal <| _div [ Attr.wrap "fsharp" ] []
        _div [ _onabort_ "fsharp" ] [] |> should equal <| _div [ Attr.onabort "fsharp" ] []
        _div [ _onafterprint_ "fsharp" ] [] |> should equal <| _div [ Attr.onafterprint "fsharp" ] []
        _div [ _onanimationend_ "fsharp" ] [] |> should equal <| _div [ Attr.onanimationend "fsharp" ] []
        _div [ _onanimationiteration_ "fsharp" ] [] |> should equal <| _div [ Attr.onanimationiteration "fsharp" ] []
        _div [ _onanimationstart_ "fsharp" ] [] |> should equal <| _div [ Attr.onanimationstart "fsharp" ] []
        _div [ _onbeforeprint_ "fsharp" ] [] |> should equal <| _div [ Attr.onbeforeprint "fsharp" ] []
        _div [ _onbeforeunload_ "fsharp" ] [] |> should equal <| _div [ Attr.onbeforeunload "fsharp" ] []
        _div [ _onblur_ "fsharp" ] [] |> should equal <| _div [ Attr.onblur "fsharp" ] []
        _div [ _oncanplay_ "fsharp" ] [] |> should equal <| _div [ Attr.oncanplay "fsharp" ] []
        _div [ _oncanplaythrough_ "fsharp" ] [] |> should equal <| _div [ Attr.oncanplaythrough "fsharp" ] []
        _div [ _onchange_ "fsharp" ] [] |> should equal <| _div [ Attr.onchange "fsharp" ] []
        _div [ _onclick_ "fsharp" ] [] |> should equal <| _div [ Attr.onclick "fsharp" ] []
        _div [ _oncontextmenu_ "fsharp" ] [] |> should equal <| _div [ Attr.oncontextmenu "fsharp" ] []
        _div [ _oncopy_ "fsharp" ] [] |> should equal <| _div [ Attr.oncopy "fsharp" ] []
        _div [ _oncut_ "fsharp" ] [] |> should equal <| _div [ Attr.oncut "fsharp" ] []
        _div [ _ondblclick_ "fsharp" ] [] |> should equal <| _div [ Attr.ondblclick "fsharp" ] []
        _div [ _ondrag_ "fsharp" ] [] |> should equal <| _div [ Attr.ondrag "fsharp" ] []
        _div [ _ondragend_ "fsharp" ] [] |> should equal <| _div [ Attr.ondragend "fsharp" ] []
        _div [ _ondragenter_ "fsharp" ] [] |> should equal <| _div [ Attr.ondragenter "fsharp" ] []
        _div [ _ondragleave_ "fsharp" ] [] |> should equal <| _div [ Attr.ondragleave "fsharp" ] []
        _div [ _ondragover_ "fsharp" ] [] |> should equal <| _div [ Attr.ondragover "fsharp" ] []
        _div [ _ondragstart_ "fsharp" ] [] |> should equal <| _div [ Attr.ondragstart "fsharp" ] []
        _div [ _ondrop_ "fsharp" ] [] |> should equal <| _div [ Attr.ondrop "fsharp" ] []
        _div [ _ondurationchange_ "fsharp" ] [] |> should equal <| _div [ Attr.ondurationchange "fsharp" ] []
        _div [ _onemptied_ "fsharp" ] [] |> should equal <| _div [ Attr.onemptied "fsharp" ] []
        _div [ _onended_ "fsharp" ] [] |> should equal <| _div [ Attr.onended "fsharp" ] []
        _div [ _onerror_ "fsharp" ] [] |> should equal <| _div [ Attr.onerror "fsharp" ] []
        _div [ _onfocus_ "fsharp" ] [] |> should equal <| _div [ Attr.onfocus "fsharp" ] []
        _div [ _onformchange_ "fsharp" ] [] |> should equal <| _div [ Attr.onformchange "fsharp" ] []
        _div [ _onforminput_ "fsharp" ] [] |> should equal <| _div [ Attr.onforminput "fsharp" ] []
        _div [ _onfocusin_ "fsharp" ] [] |> should equal <| _div [ Attr.onfocusin "fsharp" ] []
        _div [ _onfocusout_ "fsharp" ] [] |> should equal <| _div [ Attr.onfocusout "fsharp" ] []
        _div [ _onfullscreenchange_ "fsharp" ] [] |> should equal <| _div [ Attr.onfullscreenchange "fsharp" ] []
        _div [ _onfullscreenerror_ "fsharp" ] [] |> should equal <| _div [ Attr.onfullscreenerror "fsharp" ] []
        _div [ _onhashchange_ "fsharp" ] [] |> should equal <| _div [ Attr.onhashchange "fsharp" ] []
        _div [ _oninput_ "fsharp" ] [] |> should equal <| _div [ Attr.oninput "fsharp" ] []
        _div [ _oninvalid_ "fsharp" ] [] |> should equal <| _div [ Attr.oninvalid "fsharp" ] []
        _div [ _onkeydown_ "fsharp" ] [] |> should equal <| _div [ Attr.onkeydown "fsharp" ] []
        _div [ _onkeypress_ "fsharp" ] [] |> should equal <| _div [ Attr.onkeypress "fsharp" ] []
        _div [ _onkeyup_ "fsharp" ] [] |> should equal <| _div [ Attr.onkeyup "fsharp" ] []
        _div [ _onload_ "fsharp" ] [] |> should equal <| _div [ Attr.onload "fsharp" ] []
        _div [ _onloadeddata_ "fsharp" ] [] |> should equal <| _div [ Attr.onloadeddata "fsharp" ] []
        _div [ _onloadedmetadata_ "fsharp" ] [] |> should equal <| _div [ Attr.onloadedmetadata "fsharp" ] []
        _div [ _onloadstart_ "fsharp" ] [] |> should equal <| _div [ Attr.onloadstart "fsharp" ] []
        _div [ _onmessage_ "fsharp" ] [] |> should equal <| _div [ Attr.onmessage "fsharp" ] []
        _div [ _onmousedown_ "fsharp" ] [] |> should equal <| _div [ Attr.onmousedown "fsharp" ] []
        _div [ _onmouseenter_ "fsharp" ] [] |> should equal <| _div [ Attr.onmouseenter "fsharp" ] []
        _div [ _onmouseleave_ "fsharp" ] [] |> should equal <| _div [ Attr.onmouseleave "fsharp" ] []
        _div [ _onmousemove_ "fsharp" ] [] |> should equal <| _div [ Attr.onmousemove "fsharp" ] []
        _div [ _onmouseover_ "fsharp" ] [] |> should equal <| _div [ Attr.onmouseover "fsharp" ] []
        _div [ _onmouseout_ "fsharp" ] [] |> should equal <| _div [ Attr.onmouseout "fsharp" ] []
        _div [ _onmouseup_ "fsharp" ] [] |> should equal <| _div [ Attr.onmouseup "fsharp" ] []
        _div [ _onmousewheel_ "fsharp" ] [] |> should equal <| _div [ Attr.onmousewheel "fsharp" ] []
        _div [ _onoffline_ "fsharp" ] [] |> should equal <| _div [ Attr.onoffline "fsharp" ] []
        _div [ _ononline_ "fsharp" ] [] |> should equal <| _div [ Attr.ononline "fsharp" ] []
        _div [ _onopen_ "fsharp" ] [] |> should equal <| _div [ Attr.onopen "fsharp" ] []
        _div [ _onpagehide_ "fsharp" ] [] |> should equal <| _div [ Attr.onpagehide "fsharp" ] []
        _div [ _onpageshow_ "fsharp" ] [] |> should equal <| _div [ Attr.onpageshow "fsharp" ] []
        _div [ _onpaste_ "fsharp" ] [] |> should equal <| _div [ Attr.onpaste "fsharp" ] []
        _div [ _onpause_ "fsharp" ] [] |> should equal <| _div [ Attr.onpause "fsharp" ] []
        _div [ _onplay_ "fsharp" ] [] |> should equal <| _div [ Attr.onplay "fsharp" ] []
        _div [ _onplaying_ "fsharp" ] [] |> should equal <| _div [ Attr.onplaying "fsharp" ] []
        _div [ _onpopstate_ "fsharp" ] [] |> should equal <| _div [ Attr.onpopstate "fsharp" ] []
        _div [ _onprogress_ "fsharp" ] [] |> should equal <| _div [ Attr.onprogress "fsharp" ] []
        _div [ _onratechange_ "fsharp" ] [] |> should equal <| _div [ Attr.onratechange "fsharp" ] []
        _div [ _onresize_ "fsharp" ] [] |> should equal <| _div [ Attr.onresize "fsharp" ] []
        _div [ _onreset_ "fsharp" ] [] |> should equal <| _div [ Attr.onreset "fsharp" ] []
        _div [ _onscroll_ "fsharp" ] [] |> should equal <| _div [ Attr.onscroll "fsharp" ] []
        _div [ _onsearch_ "fsharp" ] [] |> should equal <| _div [ Attr.onsearch "fsharp" ] []
        _div [ _onseeked_ "fsharp" ] [] |> should equal <| _div [ Attr.onseeked "fsharp" ] []
        _div [ _onseeking_ "fsharp" ] [] |> should equal <| _div [ Attr.onseeking "fsharp" ] []
        _div [ _onselect_ "fsharp" ] [] |> should equal <| _div [ Attr.onselect "fsharp" ] []
        _div [ _onshow_ "fsharp" ] [] |> should equal <| _div [ Attr.onshow "fsharp" ] []
        _div [ _onstalled_ "fsharp" ] [] |> should equal <| _div [ Attr.onstalled "fsharp" ] []
        _div [ _onstorage_ "fsharp" ] [] |> should equal <| _div [ Attr.onstorage "fsharp" ] []
        _div [ _onsubmit_ "fsharp" ] [] |> should equal <| _div [ Attr.onsubmit "fsharp" ] []
        _div [ _onsuspend_ "fsharp" ] [] |> should equal <| _div [ Attr.onsuspend "fsharp" ] []
        _div [ _ontimeupdate_ "fsharp" ] [] |> should equal <| _div [ Attr.ontimeupdate "fsharp" ] []
        _div [ _ontoggle_ "fsharp" ] [] |> should equal <| _div [ Attr.ontoggle "fsharp" ] []
        _div [ _ontouchcancel_ "fsharp" ] [] |> should equal <| _div [ Attr.ontouchcancel "fsharp" ] []
        _div [ _ontouchend_ "fsharp" ] [] |> should equal <| _div [ Attr.ontouchend "fsharp" ] []
        _div [ _ontouchmove_ "fsharp" ] [] |> should equal <| _div [ Attr.ontouchmove "fsharp" ] []
        _div [ _ontouchstart_ "fsharp" ] [] |> should equal <| _div [ Attr.ontouchstart "fsharp" ] []
        _div [ _ontransitionend_ "fsharp" ] [] |> should equal <| _div [ Attr.ontransitionend "fsharp" ] []
        _div [ _onunload_ "fsharp" ] [] |> should equal <| _div [ Attr.onunload "fsharp" ] []
        _div [ _onvolumechange_ "fsharp" ] [] |> should equal <| _div [ Attr.onvolumechange "fsharp" ] []
        _div [ _onwaiting_ "fsharp" ] [] |> should equal <| _div [ Attr.onwaiting "fsharp" ] []
        _div [ _onwheel_ "fsharp" ] [] |> should equal <| _div [ Attr.onwheel "fsharp" ] []
